//! `trace read` — cleaned file/method/range reads, worktree or git ref.
//! Method-by-name resolution and the symbol-diff body comparison are
//! AST-derived via `crate::ccn` (name -> line span). Supports fluff
//! stripping, ref loading, line/anchor scoping, and nested-memory loading.

use super::{nested_memory, session_log};
use crate::{cache, ccn, extraction, file_facts, passive_context, relations};
use anyhow::Result;
use regex::Regex;
use serde_json::{json, Value};
use std::borrow::Cow;
use std::io::Write;
use std::path::Path;
use std::process::Command;

/// Resolve whether `read` injects project-docs. Off by default; only an
/// explicit `--docs` turns it on.
fn docs_enabled(docs_override: Option<bool>) -> bool {
    docs_override == Some(true)
}

const GENERATED_MARKERS: &[&str] = &[
    "auto-generated",
    "automatically generated",
    "generated by",
    "this file is generated",
];
const LICENSE_MARKERS: &[&str] = &[
    "license:",
    "licensed under",
    "spdx-license-identifier:",
    "copyright (c)",
    "copyright ©",
    "all rights reserved",
];

/// Bytes of rendered content one file may emit before the trim marker.
/// Claude Code budgets a Bash result at 30,000 characters and writes
/// anything larger to a spill file the agent must fetch in a second call;
/// codex truncates the middle in place with no line numbers. Neither tells
/// the agent where the cut landed. This sits under both with headroom for
/// the shoulder line and a `--docs` block, so a trimmed read arrives whole
/// and says how to continue.
const READ_CONTENT_BUDGET_CHARS: usize = 24_000;

fn separator_re() -> &'static Regex {
    use std::sync::OnceLock;
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^[\s#/*\-=_*~]{8,}$").unwrap())
}

fn is_decorative_separator(line: &str) -> bool {
    let stripped = line.trim();
    !stripped.is_empty() && separator_re().is_match(stripped)
}

type SourceLine<'a> = (usize, &'a str);
type RenderedLine<'a> = (usize, Cow<'a, str>);

struct RenderedRead {
    payload: Value,
    memories: Vec<nested_memory::LoadedMemory>,
    file_path: std::path::PathBuf,
    content_hash: String,
    content_size: usize,
    total_lines: usize,
    delivered_spans: Vec<(usize, usize)>,
}

fn comment_syntax(file: &str) -> (Option<&'static str>, Option<(&'static str, &'static str)>) {
    let extension = Path::new(file)
        .extension()
        .and_then(|value| value.to_str())
        .unwrap_or("")
        .to_ascii_lowercase();
    if matches!(
        extension.as_str(),
        "html" | "htm" | "xml" | "md" | "markdown"
    ) {
        (None, Some(("<!--", "-->")))
    } else if matches!(
        extension.as_str(),
        "py" | "pyi"
            | "rb"
            | "sh"
            | "bash"
            | "zsh"
            | "yaml"
            | "yml"
            | "toml"
            | "lock"
            | "pl"
            | "pm"
            | "r"
            | "conf"
            | "ex"
            | "exs"
    ) {
        (Some("#"), None)
    } else if matches!(extension.as_str(), "sql" | "lua" | "hs") {
        (Some("--"), None)
    } else if matches!(extension.as_str(), "ini" | "cfg") {
        (Some(";"), None)
    } else if extension == "css" {
        (None, Some(("/*", "*/")))
    } else if matches!(
        extension.as_str(),
        "rs" | "js"
            | "cjs"
            | "mjs"
            | "jsx"
            | "ts"
            | "cts"
            | "mts"
            | "tsx"
            | "c"
            | "h"
            | "cc"
            | "cpp"
            | "cxx"
            | "hpp"
            | "java"
            | "go"
            | "swift"
            | "kt"
            | "kts"
            | "php"
            | "phtml"
            | "cs"
            | "scala"
            | "sc"
            | "dart"
    ) {
        (Some("//"), Some(("/*", "*/")))
    } else {
        (None, None)
    }
}

fn is_header_notice(line: &str) -> bool {
    let lower = line
        .trim()
        .trim_start_matches('*')
        .trim_start()
        .to_lowercase()
        .replace("@generated", "generated");
    let starts_with_phrase = |phrase: &str| {
        lower.strip_prefix(phrase).is_some_and(|rest| {
            rest.chars()
                .next()
                .is_none_or(|character| !character.is_alphanumeric() && character != '_')
        })
    };
    LICENSE_MARKERS
        .iter()
        .any(|marker| starts_with_phrase(marker))
        || GENERATED_MARKERS
            .iter()
            .any(|marker| starts_with_phrase(marker))
        || starts_with_phrase("code generated by")
        || starts_with_phrase("this file is automatically generated")
}

fn is_lua_long_comment_open(line: &str) -> bool {
    let Some(rest) = line.trim_start().strip_prefix("--[") else {
        return false;
    };
    rest.trim_start_matches('=').starts_with('[')
}

fn source_lines(source: &str) -> impl Iterator<Item = (usize, &str)> {
    source
        .split_inclusive('\n')
        .enumerate()
        .map(|(index, line)| (index + 1, line))
}

fn has_bare_carriage_return(line: &str) -> bool {
    line.as_bytes()
        .iter()
        .enumerate()
        .any(|(index, byte)| *byte == b'\r' && line.as_bytes().get(index + 1) != Some(&b'\n'))
}

fn leading_header_lines(source: &str, file: &str) -> Vec<(usize, usize)> {
    let (line_prefix, block) = comment_syntax(file);
    let is_lua = Path::new(file)
        .extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| extension.eq_ignore_ascii_case("lua"));
    let mut removed = Vec::new();
    let mut lines = source_lines(source).peekable();
    if lines.peek().is_some_and(|(_, line)| line.starts_with("#!")) {
        lines.next();
    }

    loop {
        while lines.peek().is_some_and(|(_, line)| line.trim().is_empty()) {
            lines.next();
        }
        let Some(&(number, line)) = lines.peek() else {
            break;
        };

        let trimmed = line.trim_start();
        if let Some(prefix) = line_prefix.filter(|prefix| trimmed.starts_with(prefix)) {
            let start = number;
            let mut end = number;
            let mut notice = false;
            while let Some(&(current, candidate)) = lines.peek() {
                let Some(text) = candidate.trim_start().strip_prefix(prefix) else {
                    break;
                };
                if has_bare_carriage_return(candidate)
                    || is_lua && is_lua_long_comment_open(candidate)
                {
                    return removed;
                }
                notice |= is_header_notice(text);
                end = current;
                lines.next();
            }
            if notice {
                removed.push((start, end));
            }
            continue;
        }

        if let Some((open, close)) = block.filter(|(open, _)| trimmed.starts_with(open)) {
            let start = number;
            let mut end = number;
            let mut notice = false;
            let mut complete = false;
            while let Some((current, candidate)) = lines.next() {
                if has_bare_carriage_return(candidate) {
                    return removed;
                }
                end = current;
                let candidate = candidate.trim_end_matches(['\r', '\n']);
                let text = if current == start {
                    candidate
                        .trim_start()
                        .strip_prefix(open)
                        .unwrap_or(candidate)
                } else {
                    candidate
                };
                if text.contains(open) {
                    return removed;
                }
                if let Some((before, after)) = text.split_once(close) {
                    if !after.trim().is_empty() {
                        return removed;
                    }
                    notice |= is_header_notice(before);
                    complete = true;
                    break;
                }
                notice |= is_header_notice(text);
            }
            if !complete {
                return removed;
            }
            if notice {
                removed.push((start, end));
            }
            continue;
        }

        break;
    }
    removed
}

fn clean<'a>(mut pairs: Vec<SourceLine<'a>>, source: &str, file: &str) -> Vec<RenderedLine<'a>> {
    let header_lines = leading_header_lines(source, file);
    pairs.retain(|(line, _)| {
        !header_lines
            .iter()
            .any(|(start, end)| line >= start && line <= end)
    });
    pairs.retain(|(_, line)| !is_decorative_separator(line));
    let mut blank_run = 0;
    pairs.retain(|(_, line)| {
        if line.trim().is_empty() {
            blank_run += 1;
            blank_run <= 2
        } else {
            blank_run = 0;
            true
        }
    });
    let width = pairs
        .iter()
        .map(|(n, _)| n.to_string().len())
        .max()
        .unwrap_or(1);
    pairs
        .into_iter()
        .map(|(number, line)| {
            if line.trim().is_empty() {
                (number, Cow::Borrowed(line))
            } else {
                (
                    number,
                    Cow::Owned(format!("L{:>width$}: {}", number, line, width = width)),
                )
            }
        })
        .collect()
}

/// Lines in `content`, where a trailing newline does not open a new line.
fn line_count(content: &str) -> usize {
    source_lines(content).count()
}

/// Trim rendered content to the last whole line fitting in `budget`, and
/// retain the source position each emitted line carries. Returns whether
/// anything was dropped. A first line larger than the whole budget remains
/// whole and unmarked.
fn trim_to_budget(lines: &mut Vec<RenderedLine<'_>>, budget: usize) -> bool {
    let mut bytes = 0usize;
    let mut keep = 0usize;
    for (_, line) in lines.iter() {
        if keep > 0 && bytes + line.len() > budget {
            break;
        }
        bytes += line.len();
        keep += 1;
    }
    if keep == lines.len() {
        return false;
    }
    lines.truncate(keep);
    true
}

/// The inline trim marker. It sits in the content stream itself, at the
/// end, so an agent reading top-to-bottom reaches it and no consumer can
/// drop it.
fn trim_marker(
    file: &str,
    flags: &str,
    last_line: usize,
    selection_end: usize,
    total_lines: usize,
) -> String {
    if last_line >= selection_end {
        return format!("\n[trimmed at L{last_line} of {total_lines}]\n");
    }
    // A path carrying whitespace has to survive being pasted into a shell.
    let quoted = if file.contains(char::is_whitespace) {
        format!("'{}'", file.replace('\'', r"'\''"))
    } else {
        file.to_string()
    };
    format!(
        "\n[trimmed at L{last_line} of {total_lines} — continue: trace read {quoted} --lines {}:{}{flags}]\n",
        last_line + 1,
        selection_end
    )
}

/// Find `method_name` in `source` via the AST CCN backend and return its
/// source lines. Matches exact name or qualified suffix. Leading
/// comment lines directly above the symbol are pulled in via walk-back.
fn extract_method_from_source<'a>(
    source: &'a str,
    file_for_language: &str,
    method_name: &str,
) -> Option<Vec<SourceLine<'a>>> {
    let functions = ccn::analyze(source.as_bytes(), file_for_language)?;
    let suffix = format!(".{method_name}");
    let target = functions
        .iter()
        .find(|f| f.name == method_name || f.name.ends_with(&suffix))?;
    let lines: Vec<SourceLine<'a>> = source_lines(source).collect();
    let mut start = (target.start_line - 1).max(0) as usize;
    let end_line = target.start_line + target.nloc - 1;
    let end = (end_line as usize).min(lines.len());

    // Pull in a comment block directly attached to the symbol. A blank
    // line terminates the block UNLESS a comment continues above the blank
    // run (a comment block with an internal blank line stays whole). This
    // is what stops a plain blank-line separator above the symbol from
    // being dragged in as if it were a leading comment.
    let is_comment = |s: &str| {
        let t = s.trim();
        t.starts_with('#') || t.starts_with("//") || t.starts_with('*') || t.starts_with("/*")
    };
    while start > 0 {
        let prev = lines[start - 1].1;
        if is_comment(prev) {
            start -= 1;
            continue;
        }
        if prev.trim().is_empty() {
            // Look above the blank run: only cross it if the block of
            // comments continues, otherwise the blank line is a separator
            // and the comment block (if any) has ended.
            let mut above = start - 1;
            while above > 0 && lines[above - 1].1.trim().is_empty() {
                above -= 1;
            }
            if above > 0 && is_comment(lines[above - 1].1) {
                start = above - 1;
                continue;
            }
        }
        break;
    }
    Some(lines[start..end].to_vec())
}

fn apply_line_range(source: &str, l1: i64, l2: i64) -> Vec<SourceLine<'_>> {
    let total = source_lines(source).count();
    if total == 0 {
        return Vec::new();
    }
    let start_idx = (l1 - 1).max(0) as usize;
    let end_idx = (l2 as usize).min(total);
    if start_idx >= end_idx {
        return Vec::new();
    }
    source_lines(source)
        .skip(start_idx)
        .take(end_idx - start_idx)
        .collect()
}

fn compile_anchor(anchor: &str) -> Regex {
    Regex::new(anchor).unwrap_or_else(|_| Regex::new(&regex::escape(anchor)).unwrap())
}

fn apply_between<'a>(
    source: &'a str,
    start_anchor: &str,
    end_anchor: &str,
) -> Option<Vec<SourceLine<'a>>> {
    let start_re = compile_anchor(start_anchor);
    let end_re = compile_anchor(end_anchor);
    let lines: Vec<SourceLine<'a>> = source_lines(source).collect();
    let start_idx = lines
        .iter()
        .position(|(_, line)| start_re.is_match(line.strip_suffix('\n').unwrap_or(line)));
    let start_idx = start_idx?;
    let end_idx = lines
        .iter()
        .enumerate()
        .skip(start_idx + 1)
        .find_map(|(index, (_, line))| {
            end_re
                .is_match(line.strip_suffix('\n').unwrap_or(line))
                .then_some(index + 1)
        })
        .unwrap_or(lines.len());
    Some(lines[start_idx..end_idx].to_vec())
}

/// Parse a `L1:L2` range. A malformed or invalid range is a user-input
/// error, so it exits 2 with an explicit stderr message — the same
/// contract every other bad-argument path in this command uses (unknown
/// ref, missing method, `--diff` without `--at`). Returning an `anyhow`
/// error here would exit 1 and break that contract.
fn parse_lines(value: &str) -> (i64, i64) {
    let re = Regex::new(r"^(\d+):(\d+)$").unwrap();
    let caps = match re.captures(value) {
        Some(c) => c,
        None => {
            eprintln!("Error: expected format L1:L2 (1-indexed inclusive), got '{value}'");
            std::process::exit(2);
        }
    };
    let l1: i64 = caps[1].parse().unwrap();
    let l2: i64 = caps[2].parse().unwrap();
    if l1 < 1 {
        eprintln!("Error: line numbers must be >= 1 (got {l1})");
        std::process::exit(2);
    }
    if l2 < l1 {
        eprintln!("Error: end line {l2} must be >= start line {l1}");
        std::process::exit(2);
    }
    (l1, l2)
}

fn resolve_ref(ref_: &str, repo_root: &Path) -> Option<Value> {
    let out = Command::new("git")
        .args([
            "log",
            "-1",
            "--pretty=format:%H|%h|%ad|%s",
            "--date=short",
            ref_,
        ])
        .current_dir(repo_root)
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8_lossy(&out.stdout);
    let s = s.trim();
    if !s.contains('|') {
        return None;
    }
    let parts: Vec<&str> = s.splitn(4, '|').collect();
    if parts.len() < 4 {
        return None;
    }
    Some(json!({
        "full_sha": parts[0],
        "short_sha": parts[1],
        "date": parts[2],
        "subject": parts[3],
    }))
}

fn load_at_ref(ref_: &str, repo_root: &Path, relative: &str) -> Option<String> {
    let out = Command::new("git")
        .args(["show", &format!("{ref_}:{relative}")])
        .current_dir(repo_root)
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    Some(String::from_utf8_lossy(&out.stdout).to_string())
}

/// Function name -> (start_line, end_line) via the AST CCN backend, used
/// by the symbol-diff body comparison.
fn functions_map(
    source: Option<&str>,
    relative: &str,
) -> std::collections::HashMap<String, (i64, i64)> {
    let mut m = std::collections::HashMap::new();
    let src = match source {
        Some(s) => s,
        None => return m,
    };
    if let Some(fns) = ccn::analyze(src.as_bytes(), relative) {
        for f in fns {
            m.insert(f.name.clone(), (f.start_line, f.start_line + f.nloc - 1));
        }
    }
    m
}

fn exports_of(source: Option<&str>, relative: &str) -> Vec<Value> {
    let src = match source {
        Some(s) => s,
        None => return vec![],
    };
    match extraction::extract(src.as_bytes(), relative) {
        Some(r) => r
            .exports
            .iter()
            .map(|e| json!({"name": e.name, "kind": e.kind, "line": e.line}))
            .collect(),
        None => vec![],
    }
}

fn symbol_diff(
    ref_source: Option<&str>,
    worktree_source: Option<&str>,
    relative: &str,
) -> Option<Value> {
    let extension = Path::new(relative)
        .extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_lowercase());
    let ext = extension?;
    if !extraction::supported_extensions().contains(&ext.as_str()) {
        return None;
    }

    let ref_exports = exports_of(ref_source, relative);
    let work_exports = exports_of(worktree_source, relative);
    let key = |e: &Value| {
        (
            e["name"].as_str().unwrap_or("").to_string(),
            e["kind"].as_str().unwrap_or("").to_string(),
        )
    };
    let ref_keys: std::collections::BTreeSet<(String, String)> =
        ref_exports.iter().map(key).collect();
    let work_keys: std::collections::BTreeSet<(String, String)> =
        work_exports.iter().map(key).collect();

    let added: Vec<Value> = work_exports
        .iter()
        .filter(|e| !ref_keys.contains(&key(e)))
        .cloned()
        .collect();
    let removed: Vec<Value> = ref_exports
        .iter()
        .filter(|e| !work_keys.contains(&key(e)))
        .cloned()
        .collect();

    let ref_fns = functions_map(ref_source, relative);
    let work_fns = functions_map(worktree_source, relative);
    let ref_lines: Vec<&str> = ref_source
        .map(|s| s.split('\n').collect())
        .unwrap_or_default();
    let work_lines: Vec<&str> = worktree_source
        .map(|s| s.split('\n').collect())
        .unwrap_or_default();

    let mut changed: Vec<Value> = Vec::new();
    let shared: std::collections::BTreeSet<(String, String)> =
        ref_keys.intersection(&work_keys).cloned().collect();
    for (name, kind) in shared {
        let (rs, re_) = match ref_fns.get(&name) {
            Some(v) => *v,
            None => continue,
        };
        let (ws, we) = match work_fns.get(&name) {
            Some(v) => *v,
            None => continue,
        };
        let slice = |lines: &[&str], a: i64, b: i64| -> String {
            let start = (a - 1).max(0) as usize;
            let end = (b as usize).min(lines.len());
            if start >= end {
                String::new()
            } else {
                lines[start..end].join("\n")
            }
        };
        let ref_body = slice(&ref_lines, rs, re_);
        let work_body = slice(&work_lines, ws, we);
        if ref_body != work_body {
            changed.push(json!({
                "name": name,
                "kind": kind,
                "ref_line": rs,
                "worktree_line": ws,
            }));
        }
    }

    Some(json!({"added": added, "removed": removed, "changed": changed}))
}

fn render_symbol_diff(diff: &Value) -> String {
    let mut lines = vec![String::new(), "## Symbol diff (ref → worktree)".to_string()];
    let added = diff["added"].as_array().cloned().unwrap_or_default();
    let removed = diff["removed"].as_array().cloned().unwrap_or_default();
    let changed = diff["changed"].as_array().cloned().unwrap_or_default();
    if added.is_empty() && removed.is_empty() && changed.is_empty() {
        lines.push("  (no top-level symbol changes)".into());
        return lines.join("\n");
    }
    if !added.is_empty() {
        lines.push("  added:".into());
        for s in &added {
            lines.push(format!(
                "    + {} {} (L{})",
                s["kind"].as_str().unwrap_or(""),
                s["name"].as_str().unwrap_or(""),
                s["line"].as_i64().unwrap_or(0)
            ));
        }
    }
    if !removed.is_empty() {
        lines.push("  removed:".into());
        for s in &removed {
            lines.push(format!(
                "    - {} {} (L{})",
                s["kind"].as_str().unwrap_or(""),
                s["name"].as_str().unwrap_or(""),
                s["line"].as_i64().unwrap_or(0)
            ));
        }
    }
    if !changed.is_empty() {
        lines.push("  changed:".into());
        for s in &changed {
            lines.push(format!(
                "    ~ {} {} (ref L{} → worktree L{})",
                s["kind"].as_str().unwrap_or(""),
                s["name"].as_str().unwrap_or(""),
                s["ref_line"].as_i64().unwrap_or(0),
                s["worktree_line"].as_i64().unwrap_or(0)
            ));
        }
    }
    lines.join("\n")
}

fn clip(subject: &str, max_chars: usize) -> String {
    let count = subject.chars().count();
    if count <= max_chars {
        return subject.to_string();
    }
    let truncated: String = subject.chars().take(max_chars - 1).collect();
    format!("{}\u{2026}", truncated.trim_end())
}

#[allow(clippy::too_many_arguments)]
fn render_one(
    file_arg: &str,
    method: Option<&str>,
    line_range: Option<(i64, i64)>,
    between: Option<(&str, &str)>,
    ref_: Option<&str>,
    raw: bool,
    all: bool,
    as_diff: bool,
    docs_on: bool,
    session_dedupe: &mut std::collections::BTreeSet<String>,
) -> Result<RenderedRead> {
    let file_path_raw = Path::new(file_arg);
    let file_path = file_path_raw
        .canonicalize()
        .unwrap_or_else(|_| cache::absolutize(file_path_raw));
    let repo_root = if file_path.exists() {
        cache::worktree_root_for(&file_path).unwrap_or_else(|| cache::display_root(&file_path))
    } else {
        let here = Path::new(".");
        cache::worktree_root_for(here).unwrap_or_else(|| cache::display_root(here))
    };
    let relative = cache::relative_to_root(&file_path, &repo_root);

    let mut ref_meta: Option<Value> = None;
    let source: String;
    if let Some(r) = ref_ {
        match resolve_ref(r, &repo_root) {
            Some(m) => ref_meta = Some(m),
            None => {
                eprintln!("Error: unknown git ref '{r}'");
                std::process::exit(2);
            }
        }
        match load_at_ref(r, &repo_root, &relative) {
            Some(s) => source = s,
            None => {
                eprintln!("Error: '{relative}' does not exist at ref '{r}'");
                std::process::exit(2);
            }
        }
    } else {
        if !file_path.is_file() {
            eprintln!("Error: file not found: {file_arg}");
            std::process::exit(2);
        }
        source = String::from_utf8_lossy(&std::fs::read(&file_path)?).to_string();
    }

    let mut between_resolved_lines: Option<Vec<i64>> = None;
    let selected: Vec<SourceLine<'_>> = if let Some(m) = method {
        match extract_method_from_source(&source, &relative, m) {
            Some(lines) => lines,
            None => {
                eprintln!("Error: method '{m}' not found in {relative}");
                std::process::exit(2);
            }
        }
    } else if let Some((l1, l2)) = line_range {
        apply_line_range(&source, l1, l2)
    } else if let Some((a, b)) = between {
        match apply_between(&source, a, b) {
            Some(lines) => {
                between_resolved_lines = lines
                    .first()
                    .zip(lines.last())
                    .map(|((start, _), (end, _))| vec![*start as i64, *end as i64]);
                lines
            }
            None => {
                eprintln!("Error: start anchor '{a}' not found in {relative}");
                std::process::exit(2);
            }
        }
    } else {
        source_lines(&source).collect()
    };

    let start_line = selected
        .first()
        .map(|(number, _)| *number)
        .unwrap_or_else(|| line_range.map(|(l1, _)| l1 as usize).unwrap_or(1));
    let selection_end = selected
        .last()
        .map(|(number, _)| *number)
        .unwrap_or(start_line);
    let total_lines = line_count(&source);
    let content_hash = session_log::content_hash(&source);
    let content_size = source.len();
    let mut rendered: Vec<RenderedLine<'_>> = if raw {
        selected
            .into_iter()
            .map(|(number, line)| (number, Cow::Borrowed(line)))
            .collect()
    } else {
        clean(selected, &source, &relative)
    };
    let truncated = !all && trim_to_budget(&mut rendered, READ_CONTENT_BUDGET_CHARS);
    let shown_end = rendered
        .last()
        .map(|(number, _)| *number)
        .unwrap_or(selection_end);
    let mut delivered_spans = Vec::new();
    for (number, _) in &rendered {
        match delivered_spans.last_mut() {
            Some((_, end)) if *number == *end + 1 => *end = *number,
            _ => delivered_spans.push((*number, *number)),
        }
    }
    let selection_empty = rendered.is_empty();
    let mut content = String::new();
    for (_, line) in &rendered {
        content.push_str(line);
    }
    if truncated {
        if let Some(last_line) = rendered.last().map(|(number, _)| *number) {
            let mut flags = String::new();
            if let Some(r) = ref_ {
                flags.push_str(&format!(" --at {r}"));
            }
            if raw {
                flags.push_str(" --raw");
            }
            // The path the caller typed, never the repo-relative one: the
            // marker's command has to run from the caller's own directory,
            // and a file outside the repo root has no runnable relative form.
            let marker = trim_marker(file_arg, &flags, last_line, selection_end, total_lines);
            content.push_str(&marker);
        }
    }

    let mut symbol_diff_data: Option<Value> = None;
    if as_diff && ref_.is_some() {
        let worktree_source = if file_path.is_file() {
            std::fs::read(&file_path)
                .ok()
                .map(|b| String::from_utf8_lossy(&b).to_string())
        } else {
            None
        };
        symbol_diff_data =
            symbol_diff(Some(source.as_str()), worktree_source.as_deref(), &relative);
    }

    let facts = if ref_.is_none() && file_path.is_file() {
        file_facts::get(&file_path, &repo_root)
    } else {
        None
    };
    let graph = if facts.is_some() {
        relations::get(&repo_root).module_counts(&cache::relative_to_root(&file_path, &repo_root))
    } else {
        None
    };
    let context_line: Option<String> = if ref_.is_some() {
        ref_meta.as_ref().map(|m| {
            format!(
                "[source: ref {} · resolved: {} · date: {} · subject: {}]",
                m["short_sha"].as_str().unwrap_or(""),
                m["full_sha"].as_str().unwrap_or(""),
                m["date"].as_str().unwrap_or(""),
                clip(m["subject"].as_str().unwrap_or(""), 60)
            )
        })
    } else {
        facts
            .as_ref()
            .map(|f| passive_context::render(f, graph.as_ref()))
    };

    let memories = if docs_on {
        nested_memory::load_for_file(&file_path, &repo_root, session_dedupe, false)
    } else {
        Vec::new()
    };

    let display_file = cache::relative_to_root(&file_path, &repo_root);

    let mut payload = json!({
        "file": display_file,
        "method": method,
        "lines": line_range.map(|(a, b)| vec![a, b]),
        "between": between.map(|(a, b)| vec![a.to_string(), b.to_string()]),
        "between_resolved_lines": between_resolved_lines,
        "ref": ref_,
        "ref_resolved": ref_meta,
        "source": if ref_.is_some() { "ref" } else { "worktree" },
        "content": content,
        "raw": raw,
        "truncated": truncated,
        "shown_lines": if selection_empty { None } else { Some(vec![start_line as i64, shown_end as i64]) },
        "total_lines": total_lines,
        "passive_context": context_line,
        "graph": graph,
        "symbol_diff": symbol_diff_data,
    });
    if !memories.is_empty() {
        payload["nested_memories"] = json!(memories
            .iter()
            .map(|m| json!({
                "path": m.relative_path,
                "kind": m.kind,
                "size": m.size,
                "large": m.large,
                "content": m.content,
            }))
            .collect::<Vec<_>>());
    }
    Ok(RenderedRead {
        payload,
        memories,
        file_path,
        content_hash,
        content_size,
        total_lines,
        delivered_spans,
    })
}

fn emit_human(
    payload: &Value,
    memories: &[nested_memory::LoadedMemory],
    output: &mut impl Write,
) -> Result<()> {
    let mut header = format!("# {}", payload["file"].as_str().unwrap_or(""));
    if let Some(r) = payload["ref"].as_str() {
        header += &format!(" @ {r}");
    }
    if let Some(m) = payload["method"].as_str() {
        header += &format!(" :: {m}");
    } else if let Some(lines) = payload["lines"].as_array() {
        header += &format!(
            " :: L{}-L{}",
            lines[0].as_i64().unwrap_or(0),
            lines[1].as_i64().unwrap_or(0)
        );
    } else if let Some(between) = payload["between"].as_array() {
        header += &format!(
            " :: between /{}/,/{}/",
            between[0].as_str().unwrap_or(""),
            between[1].as_str().unwrap_or("")
        );
        if let Some(resolved) = payload["between_resolved_lines"].as_array() {
            header += &format!(
                " (L{}-L{})",
                resolved[0].as_i64().unwrap_or(0),
                resolved[1].as_i64().unwrap_or(0)
            );
        }
    }
    writeln!(output, "{header}")?;
    if let Some(pc) = payload["passive_context"].as_str() {
        writeln!(output, "{pc}")?;
    }
    let memories_block = if memories.is_empty() {
        String::new()
    } else {
        nested_memory::render(memories)
    };
    if !memories_block.is_empty() {
        writeln!(output, "{memories_block}")?;
        writeln!(output)?;
    }
    write!(output, "{}", payload["content"].as_str().unwrap_or(""))?;
    if !payload["symbol_diff"].is_null() {
        writeln!(output, "{}", render_symbol_diff(&payload["symbol_diff"]))?;
    }
    Ok(())
}

fn record_delivered_read(rendered: &RenderedRead) {
    for span in &rendered.delivered_spans {
        session_log::record_read(
            &rendered.file_path,
            "trace_read",
            &rendered.content_hash,
            rendered.content_size,
            rendered.total_lines,
            Some(*span),
        );
    }
}

#[allow(clippy::too_many_arguments)]
pub fn run(
    paths: &[String],
    method_flag: Option<&str>,
    as_json: bool,
    raw: bool,
    all: bool,
    ref_: Option<&str>,
    lines_arg: Option<&str>,
    between: Option<(String, String)>,
    as_diff: bool,
    docs_override: Option<bool>,
    record: bool,
    sink: &crate::output::Sink<'_>,
) -> Result<()> {
    let docs_on = docs_enabled(docs_override);
    if as_diff && ref_.is_none() {
        eprintln!("Error: --diff requires --at <ref>");
        std::process::exit(2);
    }
    if lines_arg.is_some() && between.is_some() {
        eprintln!("Error: --lines and --between are mutually exclusive");
        std::process::exit(2);
    }

    let line_range = lines_arg.map(parse_lines);

    let multi_scope = line_range.is_some() || between.is_some();
    let files: Vec<String>;
    let positional_method: Option<String>;
    if multi_scope {
        files = paths.to_vec();
        positional_method = None;
    } else {
        if paths.is_empty() {
            eprintln!("Error: missing file argument");
            std::process::exit(2);
        }
        if paths.len() > 2 {
            eprintln!(
                "Error: too many positionals — use --lines or --between for multi-file reads"
            );
            std::process::exit(2);
        }
        files = vec![paths[0].clone()];
        positional_method = paths.get(1).cloned();
    }

    if method_flag.is_some() && positional_method.is_some() {
        eprintln!("Error: --method and positional METHOD are mutually exclusive");
        std::process::exit(2);
    }
    let method = method_flag.map(|s| s.to_string()).or(positional_method);

    if method.is_some() && multi_scope {
        eprintln!("Error: METHOD is not valid with --lines or --between");
        std::process::exit(2);
    }
    if method.is_some() && files.len() > 1 {
        eprintln!("Error: METHOD requires exactly one file");
        std::process::exit(2);
    }

    let mut session_dedupe = if docs_on {
        session_log::loaded_paths()
    } else {
        std::collections::BTreeSet::new()
    };
    let between_ref = between.as_ref().map(|(a, b)| (a.as_str(), b.as_str()));

    let mut results: Vec<RenderedRead> = Vec::new();
    for f in &files {
        let rendered = render_one(
            f,
            method.as_deref(),
            line_range,
            between_ref,
            ref_,
            raw,
            all,
            as_diff,
            docs_on,
            &mut session_dedupe,
        )?;
        results.push(rendered);
    }

    // One shape for one file and for many: the rows are what was read, the
    // per-file context sits beside them keyed by path. `emit_human` still
    // reads each flat payload, so the split happens here rather than pushing
    // a second level into every renderer.
    let mut rows: Vec<Value> = Vec::with_capacity(results.len());
    let mut context = serde_json::Map::new();
    for rendered in &results {
        let payload = &rendered.payload;
        let file = payload["file"].as_str().unwrap_or("").to_string();
        rows.push(json!({
            "file": payload["file"],
            "source": payload["source"],
            "content": payload["content"],
            "truncated": payload["truncated"],
            "shown_lines": payload["shown_lines"],
            "total_lines": payload["total_lines"],
            "between_resolved_lines": payload["between_resolved_lines"],
        }));
        context.insert(
            file,
            json!({
                "shoulder": payload["passive_context"],
                "graph": payload["graph"],
                "ref_resolved": payload["ref_resolved"],
                "symbol_diff": payload["symbol_diff"],
                "nested_memories": payload["nested_memories"],
            }),
        );
    }
    let value = crate::output::document(
        json!({
            "paths": files,
            "method": method,
            "lines": line_range.map(|(a, b)| vec![a, b]),
            "between": between.as_ref().map(|(a, b)| vec![a.clone(), b.clone()]),
            "ref": ref_,
            "raw": raw,
            "all": all,
            "diff": as_diff,
        }),
        json!({"files": Value::Object(context)}),
        json!(rows),
        json!({"files": rows.len()}),
    );

    if as_json {
        sink.emit(&value)?;
        if record {
            for rendered in &results {
                if docs_on {
                    session_log::record_emission(&rendered.memories, "trace_read");
                }
                if ref_.is_none() {
                    record_delivered_read(rendered);
                }
            }
        }
        return Ok(());
    }

    let stdout = std::io::stdout();
    let mut output = std::io::BufWriter::with_capacity(64 * 1024, stdout.lock());
    for (i, rendered) in results.iter().enumerate() {
        if i > 0 {
            writeln!(output)?;
            writeln!(output, "---")?;
        }
        emit_human(&rendered.payload, &rendered.memories, &mut output)?;
        output.flush()?;
        if record {
            if docs_on {
                session_log::record_emission(&rendered.memories, "trace_read");
            }
            if ref_.is_none() {
                record_delivered_read(rendered);
            }
        }
    }
    Ok(())
}
