//! `trace read` — cleaned file/method/range reads, worktree or git ref.
//! Method-by-name resolution and the symbol-diff body comparison are
//! AST-derived via `crate::ccn` (name -> line span). Supports fluff
//! stripping, ref loading, line/anchor scoping, and nested-memory loading.

use super::{nested_memory, session_log};
use crate::{architecture, cache, ccn, extraction, file_facts, passive_context};
use anyhow::Result;
use regex::Regex;
use serde_json::{json, Value};
use std::path::Path;
use std::process::Command;

/// Resolve whether `read` injects project-docs. Off by default; only an
/// explicit `--docs` turns it on.
fn docs_enabled(docs_override: Option<bool>) -> bool {
    docs_override == Some(true)
}

const GENERATED_MARKERS: &[&str] = &[
    "do not edit",
    "do not modify",
    "auto-generated",
    "automatically generated",
    "generated by",
    "this file is generated",
];
const LICENSE_MARKERS: &[&str] = &[
    "license",
    "copyright (c)",
    "copyright ©",
    "all rights reserved",
];

/// Bytes of rendered content one file may emit before the trim marker.
/// Claude Code budgets a Bash result at 30,000 characters and writes
/// anything larger to a spill file the agent must fetch in a second call;
/// codex truncates the middle in place with no line numbers. Neither tells
/// the agent where the cut landed. This sits under both with headroom for
/// the shoulder line and a `--docs` block, so a trimmed read arrives whole
/// and says how to continue.
const READ_CONTENT_BUDGET_CHARS: usize = 24_000;

fn separator_re() -> &'static Regex {
    use std::sync::OnceLock;
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^[\s#/*\-=_*~]{8,}$").unwrap())
}

fn is_decorative_separator(line: &str) -> bool {
    let stripped = line.trim();
    !stripped.is_empty() && separator_re().is_match(stripped)
}

/// Split into lines, keeping each line's terminator.
fn splitlines_keepends(content: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut chars = content.chars().peekable();
    while let Some(c) = chars.next() {
        cur.push(c);
        if c == '\n' {
            out.push(std::mem::take(&mut cur));
        } else if c == '\r' {
            if chars.peek() == Some(&'\n') {
                cur.push(chars.next().unwrap());
            }
            out.push(std::mem::take(&mut cur));
        }
    }
    if !cur.is_empty() {
        out.push(cur);
    }
    out
}

type Pair = (usize, String);

fn strip_license_header(pairs: Vec<Pair>) -> Vec<Pair> {
    if pairs.is_empty() {
        return pairs;
    }
    let start = if pairs[0].1.starts_with("#!") { 1 } else { 0 };
    let mut end = start;
    let mut in_block = false;
    let mut block_end = start;
    let mut block_has_license = false;
    while end < (start + 30).min(pairs.len()) {
        let line = pairs[end].1.trim();
        let is_comment = line.starts_with('#')
            || line.starts_with("//")
            || line.starts_with('*')
            || line.starts_with("/*")
            || line.starts_with("\"\"\"")
            || line.starts_with("'''");
        if line.is_empty() && in_block {
            block_end = end;
            end += 1;
            continue;
        }
        if !is_comment && !line.is_empty() {
            break;
        }
        if is_comment {
            in_block = true;
            block_end = end + 1;
            let lower = line.to_lowercase();
            if LICENSE_MARKERS.iter().any(|m| lower.contains(m)) {
                block_has_license = true;
            }
        }
        end += 1;
    }
    if block_has_license {
        let mut out: Vec<Pair> = pairs[..start].to_vec();
        out.extend_from_slice(&pairs[block_end..]);
        out
    } else {
        pairs
    }
}

fn strip_generated_banners(pairs: Vec<Pair>) -> Vec<Pair> {
    pairs
        .into_iter()
        .filter(|(_, line)| {
            let lower = line.to_lowercase();
            !GENERATED_MARKERS.iter().any(|m| lower.contains(m))
        })
        .collect()
}

fn strip_decorative_separators(pairs: Vec<Pair>) -> Vec<Pair> {
    pairs
        .into_iter()
        .filter(|(_, line)| !is_decorative_separator(line))
        .collect()
}

fn collapse_blank_lines(pairs: Vec<Pair>) -> Vec<Pair> {
    let mut out = Vec::new();
    let mut blank_run = 0;
    for (n, line) in pairs {
        if line.trim().is_empty() {
            blank_run += 1;
            if blank_run <= 2 {
                out.push((n, line));
            }
        } else {
            blank_run = 0;
            out.push((n, line));
        }
    }
    out
}

fn clean(content: &str, start_line: usize) -> String {
    let raw = splitlines_keepends(content);
    let mut pairs: Vec<Pair> = raw
        .into_iter()
        .enumerate()
        .map(|(i, line)| (start_line + i, line))
        .collect();
    pairs = strip_license_header(pairs);
    pairs = strip_generated_banners(pairs);
    pairs = strip_decorative_separators(pairs);
    pairs = collapse_blank_lines(pairs);
    let width = pairs
        .iter()
        .map(|(n, _)| n.to_string().len())
        .max()
        .unwrap_or(1);
    let mut out = String::new();
    for (n, line) in &pairs {
        if line.trim().is_empty() {
            out.push_str(line);
        } else {
            out.push_str(&format!("L{:>width$}: {}", n, line, width = width));
        }
    }
    out
}

/// Lines in `content`, where a trailing newline does not open a new line.
fn line_count(content: &str) -> usize {
    if content.is_empty() {
        return 0;
    }
    let breaks = content.matches('\n').count();
    if content.ends_with('\n') {
        breaks
    } else {
        breaks + 1
    }
}

/// Recover the true file line number `clean` wrote onto a rendered line.
/// The number is right-aligned inside the prefix, so spaces may sit
/// between the `L` and the digits. Blank lines carry no prefix.
fn rendered_line_number(line: &str) -> Option<usize> {
    let rest = line.strip_prefix('L')?.trim_start();
    let digits: String = rest.chars().take_while(|c| c.is_ascii_digit()).collect();
    if digits.is_empty() || !rest[digits.len()..].starts_with(':') {
        return None;
    }
    digits.parse().ok()
}

/// Trim rendered content to the last whole line fitting in `budget`, and
/// report the true file line number that line carries. `None` when nothing
/// was dropped — either the content already fits, or its first line alone
/// is longer than the whole budget. A minified file is one such line, and
/// cutting inside it would break the `L<n>: ` format and hand back a
/// half-token, so it is emitted whole and unmarked instead.
fn trim_to_budget(content: &str, raw: bool, start_line: usize, budget: usize) -> Option<(String, usize)> {
    if content.len() <= budget {
        return None;
    }
    let mut kept = String::new();
    let mut kept_lines = 0usize;
    let mut last_numbered: Option<usize> = None;
    for line in content.split_inclusive('\n') {
        if kept_lines > 0 && kept.len() + line.len() > budget {
            break;
        }
        if let Some(n) = rendered_line_number(line) {
            last_numbered = Some(n);
        }
        kept.push_str(line);
        kept_lines += 1;
    }
    if kept.len() == content.len() {
        return None;
    }
    // `--raw` skips cleaning, so rendered lines map one-to-one onto file
    // lines and the count is exact. Cleaned output drops lines, so only
    // the prefix is exact.
    let last_line = if raw {
        start_line + kept_lines - 1
    } else {
        last_numbered.unwrap_or(start_line)
    };
    Some((kept, last_line))
}

/// The inline trim marker. It sits in the content stream itself, at the
/// end, so an agent reading top-to-bottom reaches it and no consumer can
/// drop it.
fn trim_marker(
    file: &str,
    flags: &str,
    last_line: usize,
    selection_end: usize,
    total_lines: usize,
) -> String {
    if last_line >= selection_end {
        return format!("\n[trimmed at L{last_line} of {total_lines}]\n");
    }
    // A path carrying whitespace has to survive being pasted into a shell.
    let quoted = if file.contains(char::is_whitespace) {
        format!("'{}'", file.replace('\'', r"'\''"))
    } else {
        file.to_string()
    };
    format!(
        "\n[trimmed at L{last_line} of {total_lines} — continue: trace read {quoted} --lines {}:{}{flags}]\n",
        last_line + 1,
        selection_end
    )
}

/// Find `method_name` in `source` via the AST CCN backend; return
/// (snippet, start_line). Matches exact name or qualified suffix. Leading
/// comment lines directly above the symbol are pulled in via walk-back.
fn extract_method_from_source(
    source: &str,
    file_for_language: &str,
    method_name: &str,
) -> Option<(String, usize)> {
    let functions = ccn::analyze(source.as_bytes(), file_for_language)?;
    let suffix = format!(".{method_name}");
    let target = functions
        .iter()
        .find(|f| f.name == method_name || f.name.ends_with(&suffix))?;
    let lines: Vec<&str> = source.split('\n').collect();
    let mut start = (target.start_line - 1).max(0) as usize;
    let end_line = target.start_line + target.nloc - 1;
    let end = (end_line as usize).min(lines.len());

    // Pull in a comment block directly attached to the symbol. A blank
    // line terminates the block UNLESS a comment continues above the blank
    // run (a comment block with an internal blank line stays whole). This
    // is what stops a plain blank-line separator above the symbol from
    // being dragged in as if it were a leading comment.
    let is_comment = |s: &str| {
        let t = s.trim();
        t.starts_with('#')
            || t.starts_with("//")
            || t.starts_with('*')
            || t.starts_with("/*")
    };
    while start > 0 {
        let prev = lines[start - 1];
        if is_comment(prev) {
            start -= 1;
            continue;
        }
        if prev.trim().is_empty() {
            // Look above the blank run: only cross it if the block of
            // comments continues, otherwise the blank line is a separator
            // and the comment block (if any) has ended.
            let mut above = start - 1;
            while above > 0 && lines[above - 1].trim().is_empty() {
                above -= 1;
            }
            if above > 0 && is_comment(lines[above - 1]) {
                start = above - 1;
                continue;
            }
        }
        break;
    }
    let snippet = format!("{}\n", lines[start..end].join("\n"));
    Some((snippet, start + 1))
}

fn apply_line_range(source: &str, l1: i64, l2: i64) -> (String, usize) {
    let lines: Vec<&str> = source.split('\n').collect();
    // A trailing newline does not count as an extra empty line.
    let total = if source.ends_with('\n') && !lines.is_empty() {
        lines.len() - 1
    } else {
        lines.len()
    };
    if total == 0 {
        return (String::new(), l1 as usize);
    }
    let start_idx = (l1 - 1).max(0) as usize;
    let end_idx = (l2 as usize).min(total);
    if start_idx >= end_idx {
        return (String::new(), l1 as usize);
    }
    let snippet = format!("{}\n", lines[start_idx..end_idx].join("\n"));
    (snippet, start_idx + 1)
}

fn compile_anchor(anchor: &str) -> Regex {
    Regex::new(anchor).unwrap_or_else(|_| Regex::new(&regex::escape(anchor)).unwrap())
}

fn apply_between(source: &str, start_anchor: &str, end_anchor: &str) -> Option<(String, usize)> {
    let start_re = compile_anchor(start_anchor);
    let end_re = compile_anchor(end_anchor);
    let lines: Vec<&str> = source.split('\n').collect();
    let total = if source.ends_with('\n') && !lines.is_empty() {
        lines.len() - 1
    } else {
        lines.len()
    };
    let mut start_idx: Option<usize> = None;
    for (i, line) in lines.iter().enumerate().take(total) {
        if start_re.is_match(line) {
            start_idx = Some(i);
            break;
        }
    }
    let start_idx = start_idx?;
    let mut end_idx = total;
    for (j, line) in lines.iter().enumerate().take(total).skip(start_idx + 1) {
        if end_re.is_match(line) {
            end_idx = j + 1;
            break;
        }
    }
    let snippet = format!("{}\n", lines[start_idx..end_idx].join("\n"));
    Some((snippet, start_idx + 1))
}

/// Parse a `L1:L2` range. A malformed or invalid range is a user-input
/// error, so it exits 2 with an explicit stderr message — the same
/// contract every other bad-argument path in this command uses (unknown
/// ref, missing method, `--diff` without `--at`). Returning an `anyhow`
/// error here would exit 1 and break that contract.
fn parse_lines(value: &str) -> (i64, i64) {
    let re = Regex::new(r"^(\d+):(\d+)$").unwrap();
    let caps = match re.captures(value) {
        Some(c) => c,
        None => {
            eprintln!("Error: expected format L1:L2 (1-indexed inclusive), got '{value}'");
            std::process::exit(2);
        }
    };
    let l1: i64 = caps[1].parse().unwrap();
    let l2: i64 = caps[2].parse().unwrap();
    if l1 < 1 {
        eprintln!("Error: line numbers must be >= 1 (got {l1})");
        std::process::exit(2);
    }
    if l2 < l1 {
        eprintln!("Error: end line {l2} must be >= start line {l1}");
        std::process::exit(2);
    }
    (l1, l2)
}

fn resolve_ref(ref_: &str, repo_root: &Path) -> Option<Value> {
    let out = Command::new("git")
        .args([
            "log",
            "-1",
            "--pretty=format:%H|%h|%ad|%s",
            "--date=short",
            ref_,
        ])
        .current_dir(repo_root)
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8_lossy(&out.stdout);
    let s = s.trim();
    if !s.contains('|') {
        return None;
    }
    let parts: Vec<&str> = s.splitn(4, '|').collect();
    if parts.len() < 4 {
        return None;
    }
    Some(json!({
        "full_sha": parts[0],
        "short_sha": parts[1],
        "date": parts[2],
        "subject": parts[3],
    }))
}

fn load_at_ref(ref_: &str, repo_root: &Path, relative: &str) -> Option<String> {
    let out = Command::new("git")
        .args(["show", &format!("{ref_}:{relative}")])
        .current_dir(repo_root)
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    Some(String::from_utf8_lossy(&out.stdout).to_string())
}

/// Function name -> (start_line, end_line) via the AST CCN backend, used
/// by the symbol-diff body comparison.
fn functions_map(source: Option<&str>, relative: &str) -> std::collections::HashMap<String, (i64, i64)> {
    let mut m = std::collections::HashMap::new();
    let src = match source {
        Some(s) => s,
        None => return m,
    };
    if let Some(fns) = ccn::analyze(src.as_bytes(), relative) {
        for f in fns {
            m.insert(f.name.clone(), (f.start_line, f.start_line + f.nloc - 1));
        }
    }
    m
}

fn exports_of(source: Option<&str>, relative: &str) -> Vec<Value> {
    let src = match source {
        Some(s) => s,
        None => return vec![],
    };
    match extraction::extract(src.as_bytes(), relative) {
        Some(r) => r
            .exports
            .iter()
            .map(|e| json!({"name": e.name, "kind": e.kind, "line": e.line}))
            .collect(),
        None => vec![],
    }
}

fn symbol_diff(
    ref_source: Option<&str>,
    worktree_source: Option<&str>,
    relative: &str,
) -> Option<Value> {
    let extension = Path::new(relative)
        .extension()
        .and_then(|e| e.to_str())
        .map(|e| e.to_lowercase());
    let ext = extension?;
    if !extraction::supported_extensions().contains(&ext.as_str()) {
        return None;
    }

    let ref_exports = exports_of(ref_source, relative);
    let work_exports = exports_of(worktree_source, relative);
    let key = |e: &Value| {
        (
            e["name"].as_str().unwrap_or("").to_string(),
            e["kind"].as_str().unwrap_or("").to_string(),
        )
    };
    let ref_keys: std::collections::BTreeSet<(String, String)> =
        ref_exports.iter().map(key).collect();
    let work_keys: std::collections::BTreeSet<(String, String)> =
        work_exports.iter().map(key).collect();

    let added: Vec<Value> = work_exports
        .iter()
        .filter(|e| !ref_keys.contains(&key(e)))
        .cloned()
        .collect();
    let removed: Vec<Value> = ref_exports
        .iter()
        .filter(|e| !work_keys.contains(&key(e)))
        .cloned()
        .collect();

    let ref_fns = functions_map(ref_source, relative);
    let work_fns = functions_map(worktree_source, relative);
    let ref_lines: Vec<&str> = ref_source.map(|s| s.split('\n').collect()).unwrap_or_default();
    let work_lines: Vec<&str> = worktree_source
        .map(|s| s.split('\n').collect())
        .unwrap_or_default();

    let mut changed: Vec<Value> = Vec::new();
    let shared: std::collections::BTreeSet<(String, String)> =
        ref_keys.intersection(&work_keys).cloned().collect();
    for (name, kind) in shared {
        let (rs, re_) = match ref_fns.get(&name) {
            Some(v) => *v,
            None => continue,
        };
        let (ws, we) = match work_fns.get(&name) {
            Some(v) => *v,
            None => continue,
        };
        let slice = |lines: &[&str], a: i64, b: i64| -> String {
            let start = (a - 1).max(0) as usize;
            let end = (b as usize).min(lines.len());
            if start >= end {
                String::new()
            } else {
                lines[start..end].join("\n")
            }
        };
        let ref_body = slice(&ref_lines, rs, re_);
        let work_body = slice(&work_lines, ws, we);
        if ref_body != work_body {
            changed.push(json!({
                "name": name,
                "kind": kind,
                "ref_line": rs,
                "worktree_line": ws,
            }));
        }
    }

    Some(json!({"added": added, "removed": removed, "changed": changed}))
}

fn render_symbol_diff(diff: &Value) -> String {
    let mut lines = vec![String::new(), "## Symbol diff (ref → worktree)".to_string()];
    let added = diff["added"].as_array().cloned().unwrap_or_default();
    let removed = diff["removed"].as_array().cloned().unwrap_or_default();
    let changed = diff["changed"].as_array().cloned().unwrap_or_default();
    if added.is_empty() && removed.is_empty() && changed.is_empty() {
        lines.push("  (no top-level symbol changes)".into());
        return lines.join("\n");
    }
    if !added.is_empty() {
        lines.push("  added:".into());
        for s in &added {
            lines.push(format!(
                "    + {} {} (L{})",
                s["kind"].as_str().unwrap_or(""),
                s["name"].as_str().unwrap_or(""),
                s["line"].as_i64().unwrap_or(0)
            ));
        }
    }
    if !removed.is_empty() {
        lines.push("  removed:".into());
        for s in &removed {
            lines.push(format!(
                "    - {} {} (L{})",
                s["kind"].as_str().unwrap_or(""),
                s["name"].as_str().unwrap_or(""),
                s["line"].as_i64().unwrap_or(0)
            ));
        }
    }
    if !changed.is_empty() {
        lines.push("  changed:".into());
        for s in &changed {
            lines.push(format!(
                "    ~ {} {} (ref L{} → worktree L{})",
                s["kind"].as_str().unwrap_or(""),
                s["name"].as_str().unwrap_or(""),
                s["ref_line"].as_i64().unwrap_or(0),
                s["worktree_line"].as_i64().unwrap_or(0)
            ));
        }
    }
    lines.join("\n")
}

fn clip(subject: &str, max_chars: usize) -> String {
    let count = subject.chars().count();
    if count <= max_chars {
        return subject.to_string();
    }
    let truncated: String = subject.chars().take(max_chars - 1).collect();
    format!("{}\u{2026}", truncated.trim_end())
}

fn graph_counts(file_path: &Path, repo_root: &Path) -> Option<Value> {
    let graph = architecture::load_cached(repo_root)?;
    let relative = match file_path
        .canonicalize()
        .ok()
        .and_then(|p| p.strip_prefix(repo_root.canonicalize().ok()?).ok().map(|r| r.to_path_buf()))
    {
        Some(r) => r.to_string_lossy().to_string(),
        None => return None,
    };
    let module_id = graph.file_to_module_id.get(&relative)?;
    let callers = architecture::dependents_of(&graph, module_id).len();
    let deps = architecture::dependencies_of(&graph, module_id).len();
    Some(json!({"callers": callers, "depended_on_by_modules": deps}))
}

#[allow(clippy::too_many_arguments)]
fn render_one(
    file_arg: &str,
    method: Option<&str>,
    line_range: Option<(i64, i64)>,
    between: Option<(&str, &str)>,
    ref_: Option<&str>,
    raw: bool,
    all: bool,
    as_diff: bool,
    docs_on: bool,
    session_dedupe: &mut std::collections::BTreeSet<String>,
) -> Result<(Value, Vec<nested_memory::LoadedMemory>)> {
    let file_path_raw = Path::new(file_arg);
    let file_path = file_path_raw
        .canonicalize()
        .unwrap_or_else(|_| cache::absolutize(file_path_raw));
    let repo_root = if file_path.exists() {
        cache::worktree_root_for(&file_path).unwrap_or_else(|| cache::display_root(&file_path))
    } else {
        let here = Path::new(".");
        cache::worktree_root_for(here).unwrap_or_else(|| cache::display_root(here))
    };
    let relative = cache::relative_to_root(&file_path, &repo_root);

    let mut ref_meta: Option<Value> = None;
    let source: String;
    if let Some(r) = ref_ {
        match resolve_ref(r, &repo_root) {
            Some(m) => ref_meta = Some(m),
            None => {
                eprintln!("Error: unknown git ref '{r}'");
                std::process::exit(2);
            }
        }
        match load_at_ref(r, &repo_root, &relative) {
            Some(s) => source = s,
            None => {
                eprintln!("Error: '{relative}' does not exist at ref '{r}'");
                std::process::exit(2);
            }
        }
    } else {
        if !file_path.is_file() {
            eprintln!("Error: file not found: {file_arg}");
            std::process::exit(2);
        }
        source = String::from_utf8_lossy(&std::fs::read(&file_path)?).to_string();
    }

    let mut start_line = 1usize;
    let mut between_resolved_lines: Option<Vec<i64>> = None;
    let content: String;
    if let Some(m) = method {
        match extract_method_from_source(&source, &relative, m) {
            Some((c, sl)) => {
                content = c;
                start_line = sl;
            }
            None => {
                eprintln!("Error: method '{m}' not found in {relative}");
                std::process::exit(2);
            }
        }
    } else if let Some((l1, l2)) = line_range {
        let (c, sl) = apply_line_range(&source, l1, l2);
        content = c;
        start_line = sl;
    } else if let Some((a, b)) = between {
        match apply_between(&source, a, b) {
            Some((c, sl)) => {
                let newline_count = c.matches('\n').count() as i64;
                let adjust = if c.ends_with('\n') { 1 } else { 0 };
                between_resolved_lines =
                    Some(vec![sl as i64, sl as i64 + newline_count - adjust]);
                content = c;
                start_line = sl;
            }
            None => {
                eprintln!("Error: start anchor '{a}' not found in {relative}");
                std::process::exit(2);
            }
        }
    } else {
        content = source.clone();
    }

    let selection_end = start_line + line_count(&content).max(1) - 1;
    let total_lines = line_count(&source);
    let content = if raw {
        content
    } else {
        clean(&content, start_line)
    };
    let selection_empty = content.is_empty();

    let trimmed = if all {
        None
    } else {
        trim_to_budget(&content, raw, start_line, READ_CONTENT_BUDGET_CHARS)
    };
    let truncated = trimmed.is_some();
    let mut shown_end = selection_end;
    let content = match trimmed {
        Some((kept, last_line)) => {
            shown_end = last_line;
            let mut flags = String::new();
            if let Some(r) = ref_ {
                flags.push_str(&format!(" --at {r}"));
            }
            if raw {
                flags.push_str(" --raw");
            }
            // The path the caller typed, never the repo-relative one: the
            // marker's command has to run from the caller's own directory,
            // and a file outside the repo root has no runnable relative form.
            let marker = trim_marker(file_arg, &flags, last_line, selection_end, total_lines);
            format!("{kept}{marker}")
        }
        None => content,
    };

    let mut symbol_diff_data: Option<Value> = None;
    if as_diff && ref_.is_some() {
        let worktree_source = if file_path.is_file() {
            std::fs::read(&file_path)
                .ok()
                .map(|b| String::from_utf8_lossy(&b).to_string())
        } else {
            None
        };
        symbol_diff_data = symbol_diff(
            Some(source.as_str()),
            worktree_source.as_deref(),
            &relative,
        );
    }

    let facts = if ref_.is_none() && file_path.is_file() {
        file_facts::get(&file_path, &repo_root)
    } else {
        None
    };
    let graph = if facts.is_some() {
        graph_counts(&file_path, &repo_root)
    } else {
        None
    };
    let context_line: Option<String> = if ref_.is_some() {
        ref_meta.as_ref().map(|m| {
            format!(
                "[source: ref {} · resolved: {} · date: {} · subject: {}]",
                m["short_sha"].as_str().unwrap_or(""),
                m["full_sha"].as_str().unwrap_or(""),
                m["date"].as_str().unwrap_or(""),
                clip(m["subject"].as_str().unwrap_or(""), 60)
            )
        })
    } else {
        facts
            .as_ref()
            .map(|f| passive_context::render(f, graph.as_ref()))
    };

    let memories = if docs_on {
        nested_memory::load_for_file(&file_path, &repo_root, session_dedupe, false)
    } else {
        Vec::new()
    };

    let display_file = cache::relative_to_root(&file_path, &repo_root);

    let mut payload = json!({
        "file": display_file,
        "method": method,
        "lines": line_range.map(|(a, b)| vec![a, b]),
        "between": between.map(|(a, b)| vec![a.to_string(), b.to_string()]),
        "between_resolved_lines": between_resolved_lines,
        "ref": ref_,
        "ref_resolved": ref_meta,
        "source": if ref_.is_some() { "ref" } else { "worktree" },
        "content": content,
        "raw": raw,
        "truncated": truncated,
        "shown_lines": if selection_empty { None } else { Some(vec![start_line as i64, shown_end as i64]) },
        "total_lines": total_lines,
        "passive_context": context_line,
        "graph": graph,
        "symbol_diff": symbol_diff_data,
    });
    if !memories.is_empty() {
        payload["nested_memories"] = json!(memories
            .iter()
            .map(|m| json!({
                "path": m.relative_path,
                "kind": m.kind,
                "size": m.size,
                "large": m.large,
                "content": m.content,
            }))
            .collect::<Vec<_>>());
    }
    Ok((payload, memories))
}

fn emit_human(payload: &Value, memories: &[nested_memory::LoadedMemory]) {
    let mut header = format!("# {}", payload["file"].as_str().unwrap_or(""));
    if let Some(r) = payload["ref"].as_str() {
        header += &format!(" @ {r}");
    }
    if let Some(m) = payload["method"].as_str() {
        header += &format!(" :: {m}");
    } else if let Some(lines) = payload["lines"].as_array() {
        header += &format!(
            " :: L{}-L{}",
            lines[0].as_i64().unwrap_or(0),
            lines[1].as_i64().unwrap_or(0)
        );
    } else if let Some(between) = payload["between"].as_array() {
        header += &format!(
            " :: between /{}/,/{}/",
            between[0].as_str().unwrap_or(""),
            between[1].as_str().unwrap_or("")
        );
        if let Some(resolved) = payload["between_resolved_lines"].as_array() {
            header += &format!(
                " (L{}-L{})",
                resolved[0].as_i64().unwrap_or(0),
                resolved[1].as_i64().unwrap_or(0)
            );
        }
    }
    println!("{header}");
    if let Some(pc) = payload["passive_context"].as_str() {
        println!("{pc}");
    }
    let memories_block = if memories.is_empty() {
        String::new()
    } else {
        nested_memory::render(memories)
    };
    if !memories_block.is_empty() {
        println!("{memories_block}");
        println!();
    }
    print!("{}", payload["content"].as_str().unwrap_or(""));
    if !payload["symbol_diff"].is_null() {
        println!("{}", render_symbol_diff(&payload["symbol_diff"]));
    }
}

#[allow(clippy::too_many_arguments)]
pub fn run(
    paths: &[String],
    method_flag: Option<&str>,
    as_json: bool,
    raw: bool,
    all: bool,
    ref_: Option<&str>,
    lines_arg: Option<&str>,
    between: Option<(String, String)>,
    as_diff: bool,
    docs_override: Option<bool>,
) -> Result<Value> {
    let docs_on = docs_enabled(docs_override);
    if as_diff && ref_.is_none() {
        eprintln!("Error: --diff requires --at <ref>");
        std::process::exit(2);
    }
    if lines_arg.is_some() && between.is_some() {
        eprintln!("Error: --lines and --between are mutually exclusive");
        std::process::exit(2);
    }

    let line_range = lines_arg.map(parse_lines);

    let multi_scope = line_range.is_some() || between.is_some();
    let files: Vec<String>;
    let positional_method: Option<String>;
    if multi_scope {
        files = paths.to_vec();
        positional_method = None;
    } else {
        if paths.is_empty() {
            eprintln!("Error: missing file argument");
            std::process::exit(2);
        }
        if paths.len() > 2 {
            eprintln!("Error: too many positionals — use --lines or --between for multi-file reads");
            std::process::exit(2);
        }
        files = vec![paths[0].clone()];
        positional_method = paths.get(1).cloned();
    }

    if method_flag.is_some() && positional_method.is_some() {
        eprintln!("Error: --method and positional METHOD are mutually exclusive");
        std::process::exit(2);
    }
    let method = method_flag
        .map(|s| s.to_string())
        .or(positional_method);

    if method.is_some() && multi_scope {
        eprintln!("Error: METHOD is not valid with --lines or --between");
        std::process::exit(2);
    }
    if method.is_some() && files.len() > 1 {
        eprintln!("Error: METHOD requires exactly one file");
        std::process::exit(2);
    }

    let mut session_dedupe = if docs_on {
        session_log::loaded_paths()
    } else {
        std::collections::BTreeSet::new()
    };
    let between_ref = between.as_ref().map(|(a, b)| (a.as_str(), b.as_str()));

    let mut results: Vec<(Value, Vec<nested_memory::LoadedMemory>)> = Vec::new();
    for f in &files {
        let rendered = render_one(
            f,
            method.as_deref(),
            line_range,
            between_ref,
            ref_,
            raw,
            all,
            as_diff,
            docs_on,
            &mut session_dedupe,
        )?;
        if docs_on {
            session_log::record_emission(&rendered.1, "trace_read");
        }
        results.push(rendered);
    }

    let value = if results.len() == 1 {
        results[0].0.clone()
    } else {
        json!({
            "files": results.iter().map(|(p, _): &(Value, Vec<nested_memory::LoadedMemory>)| p.clone()).collect::<Vec<_>>()
        })
    };

    if as_json {
        return Ok(value);
    }

    for (i, (payload, memories)) in results.iter().enumerate() {
        if i > 0 {
            println!();
            println!("---");
        }
        emit_human(payload, memories);
    }
    Ok(value)
}
