"""`trace read` — cleaned file or method reads.

Reads a method by name or the entire file. Strips token-wasting fluff
(license headers, generated banners, decorative separators, excessive
blank lines) while preserving meaningful comments adjacent to code.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import click
import lizard

from tracer import architecture, cache, file_facts, nested_memory, passive_context
from tracer.deps import require_dependencies

# Heuristics for fluff detection. Conservative: when in doubt, keep the line.
GENERATED_MARKERS = (
    "do not edit",
    "do not modify",
    "auto-generated",
    "automatically generated",
    "generated by",
    "this file is generated",
)
LICENSE_MARKERS = ("license", "copyright (c)", "copyright ©", "all rights reserved")
SEPARATOR_RE = re.compile(r"^[\s#/*\-=_*~]{8,}$")


def _is_decorative_separator(line: str) -> bool:
    stripped = line.strip()
    return bool(stripped) and bool(SEPARATOR_RE.match(stripped))


def _strip_license_header(pairs: list[tuple[int, str]]) -> list[tuple[int, str]]:
    """Drop a license/copyright comment block at the top of the file."""
    if not pairs:
        return pairs
    start = 1 if pairs[0][1].startswith("#!") else 0
    end = start
    in_block = False
    block_end = start
    block_has_license = False
    while end < min(start + 30, len(pairs)):
        line = pairs[end][1].strip()
        is_comment = (
            line.startswith("#") or line.startswith("//") or line.startswith("*")
            or line.startswith("/*") or line.startswith('"""') or line.startswith("'''")
        )
        if line == "" and in_block:
            block_end = end
            end += 1
            continue
        if not is_comment and not line == "":
            break
        if is_comment:
            in_block = True
            block_end = end + 1
            if any(marker in line.lower() for marker in LICENSE_MARKERS):
                block_has_license = True
        end += 1
    if block_has_license:
        return pairs[:start] + pairs[block_end:]
    return pairs


def _strip_generated_banners(pairs: list[tuple[int, str]]) -> list[tuple[int, str]]:
    return [
        (n, line) for n, line in pairs
        if not any(marker in line.lower() for marker in GENERATED_MARKERS)
    ]


def _collapse_blank_lines(pairs: list[tuple[int, str]]) -> list[tuple[int, str]]:
    """Replace runs of 3+ blank lines with 2 blank lines."""
    out: list[tuple[int, str]] = []
    blank_run = 0
    for n, line in pairs:
        if line.strip() == "":
            blank_run += 1
            if blank_run <= 2:
                out.append((n, line))
        else:
            blank_run = 0
            out.append((n, line))
    return out


def _strip_decorative_separators(pairs: list[tuple[int, str]]) -> list[tuple[int, str]]:
    return [(n, line) for n, line in pairs if not _is_decorative_separator(line)]


def _clean(content: str, start_line: int = 1) -> str:
    raw_lines = content.splitlines(keepends=True)
    pairs: list[tuple[int, str]] = [
        (start_line + i, line) for i, line in enumerate(raw_lines)
    ]
    pairs = _strip_license_header(pairs)
    pairs = _strip_generated_banners(pairs)
    pairs = _strip_decorative_separators(pairs)
    pairs = _collapse_blank_lines(pairs)
    width = max((len(str(n)) for n, _ in pairs), default=1)
    return "".join(
        f"L{n:>{width}}: {line}" if line.strip() else line
        for n, line in pairs
    )


def _extract_method(file: str, method_name: str) -> tuple[str, int] | None:
    try:
        parsed = lizard.analyze_file(file)
    except Exception:
        return None
    target = next(
        (f for f in parsed.function_list if f.name == method_name or f.name.endswith(f".{method_name}")),
        None,
    )
    if target is None:
        return None
    with open(file, encoding="utf-8", errors="replace") as fh:
        source = fh.read().splitlines()
    start = max(0, target.start_line - 1)
    end = min(len(source), target.end_line)

    while start > 0:
        prev = source[start - 1].strip()
        if prev == "" or prev.startswith("#") or prev.startswith("//") or prev.startswith("*") or prev.startswith("/*"):
            start -= 1
            continue
        break
    snippet = "\n".join(source[start:end]) + "\n"
    return snippet, start + 1


@click.command()
@click.argument("file", type=click.Path(exists=True, dir_okay=False))
@click.argument("method", required=False)
@click.option("--json", "as_json", is_flag=True, help="Machine-parseable JSON output")
@click.option("--raw", is_flag=True, help="Skip fluff stripping; return the file as-is")
def command(file: str, method: str | None, as_json: bool, raw: bool) -> None:
    """Read a method by name or the entire file.

    Strips license headers, generated banners, decorative separators, and
    excessive blank lines. Preserves docstrings and code-adjacent comments.
    """
    require_dependencies()

    # Side effect: ensure the file's cache entry is fresh. file_facts.get
    # uses the mtime fast-path on warm cache (single stat() call) and
    # re-extracts on staleness. Keeps the cache up to date opportunistically
    # so the next architecture query sees current state.
    facts = file_facts.get(file)

    start_line = 1
    if method:
        extracted = _extract_method(file, method)
        if extracted is None:
            click.echo(f"Error: method '{method}' not found in {file}", err=True)
            sys.exit(2)
        content, start_line = extracted
    else:
        with open(file, encoding="utf-8", errors="replace") as fh:
            content = fh.read()

    if not raw:
        content = _clean(content, start_line=start_line)

    file_path = Path(file).resolve()
    repo_root = cache.repo_root_for(file_path)
    graph_counts = _graph_counts(file_path, repo_root)
    context_line = (
        passive_context.render(facts, graph=graph_counts) if facts else None
    )
    session_dedupe = nested_memory.load_session_dedupe()
    memories = nested_memory.load_for_file(file_path, repo_root,
                                           session_dedupe=session_dedupe)
    nested_memory.save_session_dedupe(session_dedupe)
    memories_block = nested_memory.render(memories)

    try:
        display_file = str(file_path.relative_to(repo_root.resolve()))
    except ValueError:
        display_file = str(file_path)

    if as_json:
        click.echo(
            json.dumps(
                {
                    "file": display_file,
                    "method": method,
                    "content": content,
                    "raw": raw,
                    "passive_context": context_line,
                    "graph": graph_counts,
                    "nested_memories": [
                        {"path": m.relative_path, "kind": m.kind,
                         "size": m.size, "large": m.large, "content": m.content}
                        for m in memories
                    ],
                },
                indent=2,
            )
        )
    else:
        click.echo(f"# {display_file}{(' :: ' + method) if method else ''}")
        if context_line:
            click.echo(context_line)
        if memories_block:
            click.echo(memories_block)
            click.echo("")
        click.echo(content, nl=False)


def _graph_counts(file_path: Path, repo_root: Path) -> dict | None:
    """Quick architecture-graph caller/dependent counts for this file.

    Returns None when the file isn't in the architecture graph (e.g.
    extension without an extractor, or graph cache cold and we don't want
    to pay the build cost on a single read). Cheap when the graph is warm.
    """
    try:
        graph = architecture.load_cached(repo_root)
    except Exception:
        return None
    if graph is None:
        return None
    try:
        relative = str(file_path.relative_to(repo_root.resolve()))
    except ValueError:
        return None
    module_id = graph.file_to_module_id.get(relative)
    if not module_id:
        return None
    callers = len(architecture.dependents_of(graph, module_id))
    deps = len(architecture.dependencies_of(graph, module_id))
    return {"callers": callers, "depended_on_by_modules": deps}
